# Generated by Django 5.2.4 on 2025-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_file_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'audio'), (2, 'vidio'), (3, 'photo')], default=3, verbose_name='file_type'),
        ),
    ]
